services:
  survey-franken:
    container_name: survey-franken
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - SERVER_NAME=:80
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:80"
    volumes:
      - .:/app
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - .:/var/www/html
    networks:
      - default
      - mysql-stack_mysql_network

networks:
  default: {}
  mysql-stack_mysql_network:
    external: true
